config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
    # resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  # resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :overview, :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  # def index
  #   @bookmarks = Bookmark.all
  # end

  # def show
  #   @bookmark = Bookmark.find(params[:list_id])
  # end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h3>Add a movie to your <%= @list.name %> list</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
<%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
<%= f.submit class: "btn btn-flat" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h2>My lists</h2>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "Create a movie list", new_list_path(@list), class: "btn btn-primary" %>

app/views/lists/new.html.erb
<h2>Create a new list!</h2>

<%= simple_form_for @list do |f| %>
  <%= f.input :name, placeholder: 'Drama' %>
  <%= f.submit class: 'btn btn-flat' %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<%= pluralize(@list.movies.size, "movie") %>

<%= link_to "Add a movie", list_path(@list), class: "btn btn-primary" %>
<%= link_to "Delete this list", lists_path(@list), class: "btn btn-primary", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
<%= link_to "Back to my list", lists_path(@list), class: "btn btn-primary" %>

<% @list.movies.each do |movie| %>
  <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
            <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
    <strong><%= movie.title %> <span class="text-muted font-weight-normal">
            <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <%= movie.overview %>
<% end %>